#! /bin/bash
#
#######################################################################################################################
###INFORMATION ABOUT THE SCRIPT###
## SCRIPT INPUT  modified output of 4_count_matrix_miRNAs.py (only counts without sequence) and reference file 
##               from 1_sequence_extraction.sh
## SCRIPT OUTPUT *.counts which can be used as an input for 5_DESeq2.R 
# The sript creates count matrix for DESeq2 analysis

#######################################################################################################################
###SPECIFY DATA VARIABLES###
PROJECT_DIR=/storage/brno7-cerit/home/marek_bfu/smRNA # path to project dir
INPUT_DIR=$PROJECT_DIR/count_matrix_all # path to input filtered sequences
OUTPUT_DIR=$PROJECT_DIR/count_matrix_all # path to output sequences

#######################################################################################################################
###SCRIPT BODY###
cd $INPUT_DIR

for file in *.txt
do
  dos2unix $file
  chmod 700 $file
done

paste reference_all.txt H11_A_ATCACG_r.txt H11_B_CGATGT_r.txt P1_A_CAGATC__r.txt P1_B_ACTTGA__r.txt P3_A_GATCAG__r.txt P3_B_TAGCTT__r.txt P8_A_TTAGGC__r.txt P8_B_TGACCA__r.txt REG_A_ACAGTG_r.txt REG_B_GCCAAT_r.txt > counts_all.counts
