#! /bin/bash
#
#######################################################################################################################
###INFORMATION ABOUT THE SCRIPT###
# The script collapses identical sequeces to sinlge one while keeping information about number of reads, something
# like Tally http://wwwdev.ebi.ac.uk/enright-dev/kraken/reaper/src/reaper-latest/doc/tally.html
# sequences with only one hit are discarded

PROJECT_DIR=/storage/brno7-cerit/home/marek_bfu/smRNA # path to project dir
INPUT_DIR=$PROJECT_DIR/count_matrix_all # path to input filtered sequences
OUTPUT_DIR=$PROJECT_DIR/count_matrix_all # path to output sequences

cd $INPUT_DIR

#######################################################################################################################
###SCRIPT BODY###

for file in *.txt
do
  dos2unix $file
  chmod 700 $file
done

paste reference_all.txt H11_A_ATCACG_r.txt H11_B_CGATGT_r.txt P1_A_CAGATC__r.txt P1_B_ACTTGA__r.txt P3_A_GATCAG__r.txt P3_B_TAGCTT__r.txt P8_A_TTAGGC__r.txt P8_B_TGACCA__r.txt REG_A_ACAGTG_r.txt REG_B_GCCAAT_r.txt > counts_all.counts
